-- Question: Article Views I
-- 
-- Table: Views
-- +------------+---------+
-- | Column Name| Type    |
-- +------------+---------+
-- | article_id | int     |
-- | author_id  | int     |
-- | viewer_id  | int     |
-- | view_date  | date    |
-- +------------+---------+
-- There is no primary key; the table may have duplicate rows.
-- Each row shows that a viewer viewed an article written by some author on a certain date.
-- Note: author_id = viewer_id means the author viewed their own article.
--
-- Task: Find all authors that viewed at least one of their own articles.
-- Return the result table with column "id" sorted in ascending order.
--
-- Example:
-- Input:
-- +------------+-----------+-----------+------------+
-- | article_id | author_id | viewer_id | view_date  |
-- +------------+-----------+-----------+------------+
-- | 1          | 3         | 5         | 2019-08-01 |
-- | 1          | 3         | 6         | 2019-08-02 |
-- | 2          | 7         | 7         | 2019-08-01 |
-- | 2          | 7         | 6         | 2019-08-02 |
-- | 4          | 7         | 1         | 2019-07-22 |
-- | 3          | 4         | 4         | 2019-07-21 |
-- | 3          | 4         | 4         | 2019-07-21 |
-- +------------+-----------+-----------+------------+
--
-- Output:
-- +------+
-- | id   |
-- +------+
-- | 4    |
-- | 7    |
-- +------+
--
-- Explanation:
-- Authors 4 and 7 each viewed at least one of their own articles.
-- Duplicate views do not affect the result; each author is listed only once.
--
-- Approach:
-- We need to identify rows where author_id = viewer_id.
-- Then, select distinct author_id values and rename the column to "id".
-- Finally, sort the results in ascending order.

-- Solution:
SELECT DISTINCT author_id AS id
FROM Views
WHERE author_id = viewer_id
ORDER BY id ASC;
